
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.ToggleButton tbPump;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.ToggleButton tbHeater;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.ToggleButton tbLight;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.ToggleButton tbAux;
	
	private global::Gtk.Statusbar statusbar;
	
	private global::Gtk.Label lblIPAddress;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.Label lblTemp1;
	
	private global::Gtk.Label lblTemp2;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Button btnMaster;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Button button1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Tank Ctrl");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.tbPump = new global::Gtk.ToggleButton ();
		this.tbPump.CanFocus = true;
		this.tbPump.Name = "tbPump";
		this.tbPump.Label = global::Mono.Unix.Catalog.GetString ("Pump On");
		this.hbox2.Add (this.tbPump);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tbPump]));
		w1.PackType = ((global::Gtk.PackType)(1));
		w1.Position = 0;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.tbHeater = new global::Gtk.ToggleButton ();
		this.tbHeater.CanFocus = true;
		this.tbHeater.Name = "tbHeater";
		this.tbHeater.UseUnderline = true;
		this.tbHeater.Label = global::Mono.Unix.Catalog.GetString ("Heater On");
		this.hbox3.Add (this.tbHeater);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tbHeater]));
		w3.PackType = ((global::Gtk.PackType)(1));
		w3.Position = 0;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(5));
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.tbLight = new global::Gtk.ToggleButton ();
		this.tbLight.CanFocus = true;
		this.tbLight.Name = "tbLight";
		this.tbLight.UseUnderline = true;
		this.tbLight.Active = true;
		this.tbLight.Label = global::Mono.Unix.Catalog.GetString ("Light On");
		this.hbox6.Add (this.tbLight);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tbLight]));
		w6.PackType = ((global::Gtk.PackType)(1));
		w6.Position = 0;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.tbAux = new global::Gtk.ToggleButton ();
		this.tbAux.CanFocus = true;
		this.tbAux.Name = "tbAux";
		this.tbAux.UseUnderline = true;
		this.tbAux.Label = global::Mono.Unix.Catalog.GetString ("Aux On");
		this.hbox7.Add (this.tbAux);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.tbAux]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 0;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(4));
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.statusbar.HasResizeGrip = false;
		// Container child statusbar.Gtk.Box+BoxChild
		this.lblIPAddress = new global::Gtk.Label ();
		this.lblIPAddress.Name = "lblIPAddress";
		this.lblIPAddress.LabelProp = global::Mono.Unix.Catalog.GetString ("IP Address");
		this.statusbar.Add (this.lblIPAddress);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.lblIPAddress]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add (this.statusbar);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox5.Add (this.fixed2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed2]));
		w14.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Temp 1:");
		this.vbox7.Add (this.label8);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label8]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Temp 2:");
		this.vbox7.Add (this.label9);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label9]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox5.Add (this.vbox7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox7]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.lblTemp1 = new global::Gtk.Label ();
		this.lblTemp1.Name = "lblTemp1";
		this.lblTemp1.LabelProp = global::Mono.Unix.Catalog.GetString ("## C / ## F");
		this.vbox8.Add (this.lblTemp1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblTemp1]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.lblTemp2 = new global::Gtk.Label ();
		this.lblTemp2.Name = "lblTemp2";
		this.lblTemp2.LabelProp = global::Mono.Unix.Catalog.GetString ("## C / ## F");
		this.vbox8.Add (this.lblTemp2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblTemp2]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox5.Add (this.vbox8);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox8]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox5.Add (this.fixed1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed1]));
		w21.Position = 3;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnMaster = new global::Gtk.Button ();
		this.btnMaster.CanFocus = true;
		this.btnMaster.Name = "btnMaster";
		this.btnMaster.UseUnderline = true;
		this.btnMaster.Label = global::Mono.Unix.Catalog.GetString ("Master Off");
		this.vbox5.Add (this.btnMaster);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnMaster]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		this.hbox4.Add (this.vbox5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox4.Add (this.fixed3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed3]));
		w25.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Options");
		this.vbox6.Add (this.button1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button1]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		this.hbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
		w27.PackType = ((global::Gtk.PackType)(1));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w29.PackType = ((global::Gtk.PackType)(1));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 184;
		this.DefaultHeight = 172;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.tbPump.Clicked += new global::System.EventHandler (this.OnTbPumpClicked);
		this.tbHeater.Clicked += new global::System.EventHandler (this.OnTbHeaterClicked);
		this.tbLight.Clicked += new global::System.EventHandler (this.OnTbLightClicked);
		this.tbAux.Clicked += new global::System.EventHandler (this.OnTbAuxClicked);
		this.btnMaster.Clicked += new global::System.EventHandler (this.OnBtnMasterClicked);
	}
}
